/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gb_auth;
  GtkWidget *gb_welcome;
  GtkWidget *gb_aff;
  GtkWidget *gb_add;
  GtkWidget *gb_modifier;
  GtkWidget *gb_inscrit_window;
  GtkWidget *gb_liste;
  GtkWidget *gb_confirmer_supp;
  GtkWidget *gb_welcome_all;
  GtkWidget *MGWindowStock;
  GtkWidget *MGWindowAjout;
  GtkWidget *MGWindowEdit;
  GtkWidget *MGWindowError;
  GtkWidget *WindowMailing;
  GtkWidget *MGWindowSupp;
  GtkWidget *safaflissespacefoyer;
  GtkWidget *FS_wlc_foyer;
  GtkWidget *Home;
  GtkWidget *afficher_rec;
  

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gb_auth = create_gb_auth ();
  gtk_widget_show (gb_auth);
  /*FS_wlc_foyer=create_FS_wlc_foyer();
  gtk_widget_show(FS_wlc_foyer);*/
  /*safaflissespacefoyer = create_safaflissespacefoyer();
  gtk_widget_show(safaflissespacefoyer);*/
  /*gb_welcome = create_gb_welcome ();
  gtk_widget_show (gb_welcome);
  gb_aff = create_gb_aff ();
  gtk_widget_show (gb_aff);
  gb_add = create_gb_add ();
  gtk_widget_show (gb_add);
  gb_modifier = create_gb_modifier ();
  gtk_widget_show (gb_modifier);
  gb_inscrit_window = create_gb_inscrit_window ();
  gtk_widget_show (gb_inscrit_window);
  gb_liste = create_gb_liste ();
  gtk_widget_show (gb_liste);
  gb_confirmer_supp = create_gb_confirmer_supp ();
  gtk_widget_show (gb_confirmer_supp);
  gb_welcome_all = create_gb_welcome_all ();
  gtk_widget_show (gb_welcome_all);*/
  /*MGWindowStock = create_MGWindowStock ();
  gtk_widget_show (MGWindowStock);
  Home = create_Home ();
  gtk_widget_show (Home);
  afficher_rec = create_afficher_rec ();
  gtk_widget_show (afficher_rec);*/
  /*MGWindowAjout = create_MGWindowAjout ();
  gtk_widget_show (MGWindowAjout);
  MGWindowEdit = create_MGWindowEdit ();
  gtk_widget_show (MGWindowEdit);
  MGWindowError = create_MGWindowError ();
  gtk_widget_show (MGWindowError);
  WindowMailing = create_WindowMailing ();
  gtk_widget_show (WindowMailing);
  MGWindowSupp = create_MGWindowSupp ();
  gtk_widget_show (MGWindowSupp);*/

  gtk_main ();
  return 0;
}

